language: node_js
node_js:
  - node

cache:
  yarn: true

sudo: required

services:
  - docker
  
branches:
  only:
  - master

install: yarn install

script: yarn run build

after_script: 
  - docker build --tag "$DOCKER_REPO" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_REPO"