language: node_js
node_js:
  - node

cache:
  yarn: true

sudo: required

services:
  - docker
  
branches:
  only:
  - continuous-deployment

install: yarn install

script: yarn run build

after_script: 
  - docker build -t webserver-image
  - docker run -d -p -p 80:80 webserver-image

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_REPO